# Generated by Django 5.0.7 on 2024-07-16 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите породу",
                        max_length=100,
                        verbose_name="порода",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="введите описание",
                        null=True,
                        verbose_name="описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "порода",
                "verbose_name_plural": "породы",
            },
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите кличку",
                        max_length=100,
                        verbose_name="кличка",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="загрузите фото",
                        null=True,
                        upload_to="dogs/photo",
                        verbose_name="photo",
                    ),
                ),
                (
                    "date_born",
                    models.DateField(
                        blank=True,
                        help_text="укажите дату рожденя",
                        null=True,
                        verbose_name="дата рожденя",
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        help_text="выберите породу",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dogs.breed",
                        verbose_name="порода",
                    ),
                ),
            ],
            options={
                "verbose_name": "собака",
                "verbose_name_plural": "собаки",
            },
        ),
    ]
